name: Python Application CI
on:
   workflow_dispatch:
#on:
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run docker command
      run: |
         docker pull alpine
         docker iamges
