name: Python Application CI
on:
   workflow_dispatch:
#on:
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: python:3.8-slim-buster 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
