name: Python Application CI
on:
   workflow_dispatch:
#on:
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run docker command
      run: |
         docker build -t image-teste-1 .
         docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
         push: true
         tags: lgcosta/app:latest

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: "1.1.0"
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@v0.4.2
      with:
        args: |
         -auto-approve
